
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432


development:
  <<: *default
  database: popmenu_development

test:
  <<: *default
  database: popmenu_test

production:
  <<: *default
  database: popmenu_production
  username: popmenu
  password: <%= ENV["POPMENU_DATABASE_PASSWORD"] %>
